name: deploy to aliyun oss

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone MD5 Generator
      run: git clone https://github.com/LynnGuo666/MD5Generate.git 
      
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    
    - name: Run MD5 Generator
      run: |
          cd MD5Generate
          pip install -r requirements.txt
          cd ..
          python ./MD5Generate/main.py -c -d ./
          ls

    - name: Checkout
      uses: actions/checkout@v3

    # Setup Rclone
    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}

    # Rclone Sync
    #- name: Rclone Sync 
    #  run: |
    #      rclone copy ./ RiaAliyunOSS:/fst-static-api/ --transfers=8 --checkers=16 --exclude=.git/** --exclude=.github/**