name: deploy to aliyun oss

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup Rclone
    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}

    # Rclone Sync
    - name: Rclone Sync 
      run: |
          rclone copy ./ RiaAliyunOSS:/fst-static-api/ --transfers=8 --checkers=16 --exclude=.git/** --exclude=.github/**